### ISSUE TITLE
Wrap main menu to support Transient Help

### ISSUE THREAD

**Issue by kickingvegas** [kickingvegas/casual-calc#53]
Calc unfortunately has little to no docstrings for its commands. Because of this, Transient help (binding `?`) can not leverage this to provide help for a menu item that directly calls a Calc command.

Ask is to write wrappers for all Calc functions used by Casual.

**Comment by kickingvegas** [comment]
This is a big ticket. Got all the main menu functions wrapped (approx 19). Estimating about 187 more to go.

# Wrap Calc Functions <code>[0/17]</code>


## TODO casual-settings.el <code>[0/19]</code>

-   [ ] casual-settings.el: (&ldquo;A&rdquo; calc-algebraic-mode
-   [ ] casual-settings.el: (&ldquo;z&rdquo; &ldquo;Leading Zeroes&rdquo; calc-leading-zeros
-   [ ] casual-settings.el: (&ldquo;F&rdquo; calc-frac-mode :description casual-prefer-frac-label :transient t)
-   [ ] casual-settings.el: (&ldquo;s&rdquo; calc-symbolic-mode :description casual-symbolic-mode-label :transient t)
-   [ ] casual-settings.el: (&ldquo;p&rdquo; calc-polar-mode :description casual-cmplx-or-polar-label :transient t)
-   [ ] casual-settings.el: (&ldquo;P&rdquo; calc-precision
-   [ ] casual-settings.el: (&ldquo;S&rdquo; &ldquo;Save Calc Settings&rdquo; calc-save-modes :transient t)]
-   [ ] casual-settings.el: (&ldquo;g&rdquo; calc-group-digits
-   [ ] casual-settings.el: (&ldquo;,&rdquo; &ldquo;Set Thousands Separator&rdquo; calc-group-char :transient t)
-   [ ] casual-settings.el: (&ldquo;.&rdquo; &ldquo;Decimal Separator&rdquo; calc-point-char :transient t)
-   [ ] casual-settings.el: (&ldquo;H&rdquo; &ldquo;ℎ𝑚𝑠 Format&rdquo; calc-hms-notation
-   [ ] casual-settings.el: (&ldquo;C-M-r&rdquo; &ldquo;Calc Reset&rdquo; calc-reset :transient t)]]
-   [ ] casual-settings.el: (&ldquo;c&rdquo; calc-complex-notation
-   [ ] casual-settings.el: (&ldquo;i&rdquo; calc-i-notation
-   [ ] casual-settings.el: (&ldquo;j&rdquo; calc-j-notation
-   [ ] casual-settings.el: (&ldquo;n&rdquo; &ldquo;Normal&rdquo; calc-normal-notation :transient nil)
-   [ ] casual-settings.el: (&ldquo;f&rdquo; &ldquo;Fixed Point 𝑛&rdquo; calc-fix-notation :transient nil)
-   [ ] casual-settings.el: (&ldquo;s&rdquo; &ldquo;Scientific&rdquo; calc-sci-notation :transient nil)
-   [ ] casual-settings.el: (&ldquo;e&rdquo; &ldquo;Engineering&rdquo; calc-eng-notation :transient nil)]


## TODO casual-angle-measure.el <code>[0/3]</code>

-   [ ] casual-angle-measure.el: (&ldquo;d&rdquo; &ldquo;Degrees&rdquo; calc-degrees-mode :transient nil)
-   [ ] casual-angle-measure.el: (&ldquo;r&rdquo; &ldquo;Radians&rdquo; calc-radians-mode :transient nil)
-   [ ] casual-angle-measure.el: (&ldquo;h&rdquo; &ldquo;Degrees-Minutes-Seconds&rdquo; calc-hms-mode :transient nil)]


## TODO casual-radix.el <code>[0/5]</code>

-   [ ] casual-radix.el: (&ldquo;0&rdquo; &ldquo;Decimal&rdquo; calc-decimal-radix :transient nil)
-   [ ] casual-radix.el: (&ldquo;2&rdquo; &ldquo;Binary&rdquo; calc-binary-radix :transient nil)
-   [ ] casual-radix.el: (&ldquo;8&rdquo; &ldquo;Octal&rdquo; calc-octal-radix :transient nil)
-   [ ] casual-radix.el: (&ldquo;6&rdquo; &ldquo;Hexadecimal&rdquo; calc-hex-radix :transient nil)
-   [ ] casual-radix.el: (&ldquo;n&rdquo; &ldquo;Other base 𝑛&rdquo; calc-radix :transient nil)]


## TODO casual-stack.el <code>[0/8]</code>

-   [ ] casual-stack.el: (&ldquo;l&rdquo; &ldquo;Left&rdquo; calc-left-justify :transient t)
-   [ ] casual-stack.el: (&ldquo;c&rdquo; &ldquo;Center&rdquo; calc-center-justify :transient t)
-   [ ] casual-stack.el: (&ldquo;r&rdquo; &ldquo;Right&rdquo; calc-right-justify :transient t)]
-   [ ] casual-stack.el: (&ldquo;.&rdquo; &ldquo;At Point&rdquo; calc-truncate-stack :transient t)
-   [ ] casual-stack.el: (&ldquo;p&rdquo; &ldquo;Previous&rdquo; calc-truncate-up :transient t)
-   [ ] casual-stack.el: (&ldquo;n&rdquo; &ldquo;Next&rdquo; calc-truncate-down :transient t)]
-   [ ] casual-stack.el: (&ldquo;R&rdquo; &ldquo;Refresh&rdquo; calc-refresh :transient t)
-   [ ] casual-stack.el: (&ldquo;s&rdquo; &ldquo;Save Settings&rdquo; calc-save-modes :transient t)])


## TODO casual-trail.el <code>[0/15]</code>

-   [ ] casual-trail.el: (&ldquo;d&rdquo; &ldquo;Toggle Display&rdquo; calc-trail-display :transient t)
-   [ ] casual-trail.el: (&ldquo;t&rdquo; &ldquo;Focus to Trail&rdquo; calc-trail-in :transient t)
-   [ ] casual-trail.el: (&ldquo;c&rdquo; &ldquo;Focus to Calc&rdquo; calc-trail-out :transient t)
-   [ ] casual-trail.el: (&ldquo;<&rdquo; &ldquo;Scroll Left&rdquo; calc-trail-scroll-left :transient t)
-   [ ] casual-trail.el: (&ldquo;>&rdquo; &ldquo;Scroll Right&rdquo; calc-trail-scroll-right :transient t)
-   [ ] casual-trail.el: (&ldquo;p&rdquo; &ldquo;Previous&rdquo; calc-trail-previous :transient t)
-   [ ] casual-trail.el: (&ldquo;n&rdquo; &ldquo;Next&rdquo; calc-trail-next :transient t)
-   [ ] casual-trail.el: (&ldquo;[&rdquo; &ldquo;First&rdquo; calc-trail-first :transient t)
-   [ ] casual-trail.el: (&ldquo;]&rdquo; &ldquo;Last&rdquo; calc-trail-last :transient t)]
-   [ ] casual-trail.el: (&ldquo;m&rdquo; &ldquo;Insert Marker…&rdquo; calc-trail-marker :transient t)
-   [ ] casual-trail.el: (&ldquo;C-r&rdquo; &ldquo;isearch-backward&rdquo; calc-trail-isearch-backward :transient t)
-   [ ] casual-trail.el: (&ldquo;C-s&rdquo; &ldquo;isearch-forward&rdquo; calc-trail-isearch-forward :transient t)
-   [ ] casual-trail.el: (&ldquo;y&rdquo; &ldquo;Yank to Stack&rdquo; calc-trail-yank :transient t)
-   [ ] casual-trail.el: (&ldquo;k&rdquo; &ldquo;Kill Selected&rdquo; calc-trail-kill :transient t)
-   [ ] casual-trail.el: (&ldquo;s&rdquo; &ldquo;Save Settings&rdquo; calc-save-modes :transient t)


## TODO casual-rounding.el <code>[0/4]</code>

-   [ ] casual-rounding.el: (&ldquo;r&rdquo; &ldquo;Round&rdquo; calc-round :transient nil)
-   [ ] casual-rounding.el: (&ldquo;f&rdquo; &ldquo;Floor&rdquo; calc-floor :transient nil)
-   [ ] casual-rounding.el: (&ldquo;c&rdquo; &ldquo;Ceiling&rdquo; calc-ceiling :transient nil)
-   [ ] casual-rounding.el: (&ldquo;t&rdquo; &ldquo;Truncate&rdquo; calc-trunc :transient nil)]


## TODO casual-conversion.el <code>[0/5]</code>

-   [ ] casual-conversion.el: (&ldquo;d&rdquo; &ldquo;To Degrees&rdquo; calc-to-degrees :transient nil)
-   [ ] casual-conversion.el: (&ldquo;r&rdquo; &ldquo;To Radians&rdquo; calc-to-radians :transient nil)
-   [ ] casual-conversion.el: (&ldquo;h&rdquo; &ldquo;To HMS&rdquo; calc-to-hms :transient nil)
-   [ ] casual-conversion.el: (&ldquo;f&rdquo; &ldquo;To Float&rdquo; calc-float :transient nil)
-   [ ] casual-conversion.el: (&ldquo;F&rdquo; &ldquo;To Fraction&rdquo; calc-fraction :transient nil)]


## TODO casual-time.el <code>[0/8]</code>

-   [ ] casual-time.el: (&ldquo;n&rdquo; &ldquo;Now&rdquo; calc-now :transient nil)
-   [ ] casual-time.el: (&ldquo;i&rdquo; &ldquo;Increment Month&rdquo; calc-inc-month :transient nil)
-   [ ] casual-time.el: (&ldquo;u&rdquo; &ldquo;To Unix Time&rdquo; calc-unix-time :transient nil)
-   [ ] casual-time.el: (&ldquo;+&rdquo; &ldquo;Add Business Days&rdquo; calc-business-days-plus :transient nil)
-   [ ] casual-time.el: (&ldquo;-&rdquo; &ldquo;Subtract Business Days&rdquo; calc-business-days-minus :transient nil)]
-   [ ] casual-time.el: (&ldquo;w&rdquo; &ldquo;Week&rdquo; calc-new-week :transient nil)
-   [ ] casual-time.el: (&ldquo;m&rdquo; &ldquo;Month&rdquo; calc-new-month :transient nil)
-   [ ] casual-time.el: (&ldquo;y&rdquo; &ldquo;Year&rdquo; calc-new-year :transient nil)]


## TODO casual-complex.el <code>[0/4]</code>

-   [ ] casual-complex.el: (&ldquo;r&rdquo; &ldquo;Real Part&rdquo; calc-re :transient nil)
-   [ ] casual-complex.el: (&ldquo;i&rdquo; &ldquo;Imaginary Part&rdquo; calc-im :transient nil)
-   [ ] casual-complex.el: (&ldquo;c&rdquo; &ldquo;Complex Conjugate&rdquo; calc-conj :transient nil)
-   [ ] casual-complex.el: (&ldquo;a&rdquo; &ldquo;Argument&rdquo; calc-argument :transient nil)]


## TODO casual-random.el <code>[0/3]</code>

-   [ ] casual-random.el: (&ldquo;c&rdquo; &ldquo;Real within [𝟢.𝟢..𝟣.𝟢)&rdquo; calc-rrandom :transient t)]]
-   [ ] casual-random.el: (&ldquo;a&rdquo; &ldquo;Random number again&rdquo; calc-random-again :transient t)


## TODO casual-trigonometric.el <code>[0/12]</code>

-   [ ] casual-trigonometric.el: (&ldquo;s&rdquo; &ldquo;sin&rdquo; calc-sin :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;c&rdquo; &ldquo;cos&rdquo; calc-cos :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;t&rdquo; &ldquo;tan&rdquo; calc-tan :transient nil)]
-   [ ] casual-trigonometric.el: (&ldquo;S&rdquo; &ldquo;arcsin&rdquo; calc-arcsin :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;C&rdquo; &ldquo;arccos&rdquo; calc-arccos :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;T&rdquo; &ldquo;arctan&rdquo; calc-arctan :transient nil)]
-   [ ] casual-trigonometric.el: (&ldquo;s&rdquo; &ldquo;sinh&rdquo; calc-sinh :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;c&rdquo; &ldquo;cosh&rdquo; calc-cosh :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;t&rdquo; &ldquo;tanh&rdquo; calc-tanh :transient nil)]
-   [ ] casual-trigonometric.el: (&ldquo;S&rdquo; &ldquo;arcsinh&rdquo; calc-arcsinh :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;C&rdquo; &ldquo;arccosh&rdquo; calc-arccosh :transient nil)
-   [ ] casual-trigonometric.el: (&ldquo;T&rdquo; &ldquo;arctanh&rdquo; calc-arctanh :transient nil)


## TODO casual-logarithmic.el <code>[0/5]</code>

-   [ ] casual-logarithmic.el: (&ldquo;l&rdquo; &ldquo;𝑙𝑛&rdquo; calc-ln :transient nil)
-   [ ] casual-logarithmic.el: (&ldquo;e&rdquo; &ldquo;𝑒^𝑥&rdquo; calc-exp :transient nil)
-   [ ] casual-logarithmic.el: (&ldquo;L&rdquo; &ldquo;𝑙𝑜𝑔𝟣𝟢&rdquo; calc-log10 :transient nil)
-   [ ] casual-logarithmic.el: (&ldquo;M-l&rdquo; &ldquo;𝑙𝑜𝑔&rdquo; calc-log :transient nil)
-   [ ] casual-logarithmic.el: (&ldquo;M-e&rdquo; &ldquo;𝑒^𝑥 - 𝟣&rdquo; calc-expm1 :transient nil)]


## TODO casual-binary.el <code>[0/15]</code>

-   [ ] casual-binary.el: (&ldquo;a&rdquo; &ldquo;and&rdquo; calc-and :transient nil)
-   [ ] casual-binary.el: (&ldquo;o&rdquo; &ldquo;or&rdquo; calc-or :transient nil)
-   [ ] casual-binary.el: (&ldquo;x&rdquo; &ldquo;xor&rdquo; calc-xor :transient nil)
-   [ ] casual-binary.el: (&ldquo;-&rdquo; &ldquo;diff&rdquo; calc-diff :transient nil)
-   [ ] casual-binary.el: (&ldquo;!&rdquo; &ldquo;not&rdquo; calc-not :transient nil)]
-   [ ] casual-binary.el: (&ldquo;l&rdquo; &ldquo;binary left&rdquo; calc-lshift-binary :transient t)
-   [ ] casual-binary.el: (&ldquo;r&rdquo; &ldquo;binary right&rdquo; calc-rshift-binary :transient t)
-   [ ] casual-binary.el: (&ldquo;M-l&rdquo; &ldquo;arithmetic left&rdquo; calc-lshift-arith :transient t)
-   [ ] casual-binary.el: (&ldquo;M-r&rdquo; &ldquo;arithmetic right&rdquo; calc-rshift-arith :transient t)
-   [ ] casual-binary.el: (&ldquo;C-r&rdquo; &ldquo;rotate binary&rdquo; calc-rotate-binary :transient t)]
-   [ ] casual-binary.el: (&ldquo;z&rdquo; &ldquo;Leading Zeroes&rdquo; calc-leading-zeros
-   [ ] casual-binary.el: (casual&#x2013;checkbox-label calc-leading-zeros &ldquo;Leading Zeroes&rdquo;))
-   [ ] casual-binary.el: (&ldquo;w&rdquo; &ldquo;Set Word Size…&rdquo; calc-word-size :transient nil)
-   [ ] casual-binary.el: (&ldquo;u&rdquo; &ldquo;Unpack Bits&rdquo; calc-unpack-bits :transient nil)
-   [ ] casual-binary.el: (&ldquo;p&rdquo; &ldquo;Pack Bits&rdquo; calc-pack-bits :transient nil)]]


## TODO casual-vector.el <code>[0/61]</code>

-   [ ] casual-vector.el: (&ldquo;l&rdquo; &ldquo;Length&rdquo; calc-vlength :transient t)
-   [ ] casual-vector.el: (&ldquo;t&rdquo; &ldquo;Transpose&rdquo; calc-transpose :transient t)
-   [ ] casual-vector.el: (&ldquo;v&rdquo; &ldquo;Reverse&rdquo; calc-reverse-vector :transient t)
-   [ ] casual-vector.el: (&ldquo;o&rdquo; &ldquo;Sort&rdquo; calc-sort :transient t)
-   [ ] casual-vector.el: (&ldquo;d&rdquo; &ldquo;Deduplicate&rdquo; calc-remove-duplicates :transient t)]
-   [ ] casual-vector.el: (&ldquo;r&rdquo; &ldquo;Extract Row…&rdquo; calc-mrow :transient nil)
-   [ ] casual-vector.el: (&ldquo;c&rdquo; &ldquo;Extract Column…&rdquo; calc-mcol :transient nil)
-   [ ] casual-vector.el: (&ldquo;p&rdquo; &ldquo;Pack (𝑛)&rdquo; calc-pack :transient nil)
-   [ ] casual-vector.el: (&ldquo;u&rdquo; &ldquo;Unpack&rdquo; calc-unpack :transient nil)]]
-   [ ] casual-vector.el: (&ldquo;|&rdquo; &ldquo;Concat&rdquo; calc-concat :transient nil)
-   [ ] casual-vector.el: (&ldquo;i&rdquo; &ldquo;index (1..𝑛)…&rdquo; calc-index :transient nil)
-   [ ] casual-vector.el: (&ldquo;e&rdquo; &ldquo;Enumerate Interval&rdquo; calc-set-enumerate :transient nil)
-   [ ] casual-vector.el: (&ldquo;I&rdquo; &ldquo;Identity 𝑛…&rdquo; calc-ident :transient nil)
-   [ ] casual-vector.el: (&ldquo;d&rdquo; &ldquo;Diagonal (𝟣:)&rdquo; calc-diag :transient nil)
-   [ ] casual-vector.el: (&ldquo;b&rdquo; &ldquo;Build Vector 𝑛…&rdquo; calc-build-vector :transient nil)]
-   [ ] casual-vector.el: (&ldquo;t&rdquo; &ldquo;Transpose&rdquo; calc-transpose :transient nil)
-   [ ] casual-vector.el: (&ldquo;r&rdquo; &ldquo;Reverse&rdquo; calc-reverse-vector :transient nil)
-   [ ] casual-vector.el: (&ldquo;a&rdquo; &ldquo;Vector Arrange&rdquo; calc-arrange-vector :transient nil)
-   [ ] casual-vector.el: (&ldquo;s&rdquo; &ldquo;Sort&rdquo; calc-sort :transient nil)
-   [ ] casual-vector.el: (&ldquo;p&rdquo; &ldquo;Deduplicate&rdquo; calc-remove-duplicates :transient nil)]
-   [ ] casual-vector.el: (&ldquo;l&rdquo; &ldquo;Length&rdquo; calc-vlength :transient nil)
-   [ ] casual-vector.el: (&ldquo;c&rdquo; &ldquo;Vector Count&rdquo; calc-vector-count :transient nil)
-   [ ] casual-vector.el: (&ldquo;f&rdquo; &ldquo;Vector Find (𝟣:)&rdquo; calc-vector-find :transient nil)
-   [ ] casual-vector.el: (&ldquo;h&rdquo; &ldquo;Histogram&rdquo; calc-histogram :transient nil)]]
-   [ ] casual-vector.el: (&ldquo;t&rdquo; &ldquo;Conjugate Transpose&rdquo; calc-conj-transpose :transient nil)
-   [ ] casual-vector.el: (&ldquo;A&rdquo; &ldquo;Frobenius Norm (|𝑛|)&rdquo; calc-abs :transient nil)
-   [ ] casual-vector.el: (&ldquo;r&rdquo; &ldquo;Row Norm&rdquo; calc-rnorm :transient nil)
-   [ ] casual-vector.el: (&ldquo;c&rdquo; &ldquo;Column Norm&rdquo; calc-cnorm :transient nil)
-   [ ] casual-vector.el: (&ldquo;p&rdquo; &ldquo;RH Cross Product&rdquo; calc-cross :inapt-if-not casual-crossp :transient nil)
-   [ ] casual-vector.el: (&ldquo;k&rdquo; &ldquo;Kronecker Product&rdquo; calc-kron :inapt-if-not casual-matrixmultp :transient nil)]
-   [ ] casual-vector.el: (&ldquo;&&rdquo; &ldquo;Inverse&rdquo; calc-inv :inapt-if-not casual-square-matrixp :transient nil)
-   [ ] casual-vector.el: (&ldquo;d&rdquo; &ldquo;Determinant&rdquo; calc-mdet :inapt-if-not casual-square-matrixp :transient nil)
-   [ ] casual-vector.el: (&ldquo;l&rdquo; &ldquo;LU Decomposition&rdquo; calc-mlud :inapt-if-not casual-square-matrixp :transient nil)
-   [ ] casual-vector.el: (&ldquo;T&rdquo; &ldquo;Trace&rdquo; calc-mtrace :inapt-if-not casual-square-matrixp :transient nil)]]
-   [ ] casual-vector.el: (&ldquo;c&rdquo; &ldquo;Vector Count&rdquo; calc-vector-count :transient nil)
-   [ ] casual-vector.el: (&ldquo;s&rdquo; &ldquo;Sum&rdquo; calc-vector-sum :transient nil)
-   [ ] casual-vector.el: (&ldquo;x&rdquo; &ldquo;Max&rdquo; calc-vector-max :transient nil)
-   [ ] casual-vector.el: (&ldquo;m&rdquo; &ldquo;Mean&rdquo; calc-vector-mean :transient nil)
-   [ ] casual-vector.el: (&ldquo;e&rdquo; &ldquo;Mean Error&rdquo; calc-vector-mean-error :transient nil)
-   [ ] casual-vector.el: (&ldquo;M&rdquo; &ldquo;Median&rdquo; calc-vector-median :transient nil)
-   [ ] casual-vector.el: (&ldquo;H&rdquo; &ldquo;Harmonic Mean&rdquo; calc-vector-harmonic-mean :transient nil)
-   [ ] casual-vector.el: (&ldquo;g&rdquo; &ldquo;Geometric Mean&rdquo; calc-vector-geometric-mean :transient nil)]
-   [ ] casual-vector.el: (&ldquo;r&rdquo; &ldquo;Root Mean Square&rdquo; calc-vector-rms :transient nil)
-   [ ] casual-vector.el: (&ldquo;1&rdquo; &ldquo;Standard Deviation&rdquo; calc-vector-sdev :transient nil)
-   [ ] casual-vector.el: (&ldquo;2&rdquo; &ldquo;Population Standard Deviation&rdquo; calc-vector-pop-sdev :transient nil)
-   [ ] casual-vector.el: (&ldquo;3&rdquo; &ldquo;Variance&rdquo; calc-vector-variance :transient nil)
-   [ ] casual-vector.el: (&ldquo;4&rdquo; &ldquo;Population Variance&rdquo; calc-vector-pop-variance :transient nil)]
-   [ ] casual-vector.el: (&ldquo;5&rdquo; &ldquo;Covariance&rdquo; calc-vector-covariance :transient nil)
-   [ ] casual-vector.el: (&ldquo;6&rdquo; &ldquo;Population Covariance&rdquo; calc-vector-pop-covariance :transient nil)
-   [ ] casual-vector.el: (&ldquo;7&rdquo; &ldquo;Correlation&rdquo; calc-vector-correlation :transient nil)]]
-   [ ] casual-vector.el: (&ldquo;d&rdquo; &ldquo;Deduplicate&rdquo; calc-remove-duplicates :transient nil)
-   [ ] casual-vector.el: (&ldquo;u&rdquo; &ldquo;Union&rdquo; calc-set-union :transient nil)
-   [ ] casual-vector.el: (&ldquo;i&rdquo; &ldquo;Intersect&rdquo; calc-set-intersect :transient nil)
-   [ ] casual-vector.el: (&ldquo;-&rdquo; &ldquo;Difference&rdquo; calc-set-difference :transient nil)
-   [ ] casual-vector.el: (&ldquo;x&rdquo; &ldquo;xor&rdquo; calc-set-xor :transient nil)
-   [ ] casual-vector.el: (&ldquo;~&rdquo; &ldquo;Complement&rdquo; calc-set-complement :transient nil)
-   [ ] casual-vector.el: (&ldquo;#&rdquo; &ldquo;Cardinality&rdquo; calc-set-cardinality :transient nil)]
-   [ ] casual-vector.el: (&ldquo;m&rdquo; &ldquo;map&rdquo; calc-map :transient nil)
-   [ ] casual-vector.el: (&ldquo;r&rdquo; &ldquo;reduce&rdquo; calc-reduce :transient nil)
-   [ ] casual-vector.el: (&ldquo;a&rdquo; &ldquo;apply&rdquo; calc-apply :transient nil)
-   [ ] casual-vector.el: (&ldquo;A&rdquo; &ldquo;accumulate&rdquo; calc-accumulate :transient nil)]


## TODO casual-units.el <code>[0/7]</code>

-   [ ] casual-units.el: (&ldquo;c&rdquo; &ldquo;Convert&rdquo; calc-convert-units :transient nil)
-   [ ] casual-units.el: (&ldquo;t&rdquo; &ldquo;Convert Temperature&rdquo; calc-convert-temperature :transient nil)
-   [ ] casual-units.el: (&ldquo;b&rdquo; &ldquo;Convert to Base Unit&rdquo; calc-base-units :transient nil)
-   [ ] casual-units.el: (&ldquo;r&rdquo; &ldquo;Remove Units&rdquo; calc-remove-units :transient nil)
-   [ ] casual-units.el: (&ldquo;x&rdquo; &ldquo;Extract Units&rdquo; calc-extract-units :transient nil)
-   [ ] casual-units.el: (&ldquo;v&rdquo; &ldquo;View Units&rdquo; calc-view-units-table :transient nil)]


## TODO casual-graphics.el <code>[0/7]</code>

-   [ ] casual-graphics.el: (&ldquo;r&rdquo; &ldquo;Redraw&rdquo; calc-graph-plot :transient t)
-   [ ] casual-graphics.el: (&ldquo;c&rdquo; &ldquo;Clear&rdquo; calc-graph-clear :transient t)
-   [ ] casual-graphics.el: (&ldquo;p&rdquo; &ldquo;Print&rdquo; calc-graph-print
-   [ ] casual-graphics.el: (&ldquo;C&rdquo; &ldquo;Raw Command…&rdquo; calc-graph-command :transient nil)]]
-   [ ] casual-graphics.el: (&ldquo;d&rdquo; &ldquo;Set Device…&rdquo; calc-graph-device
-   [ ] casual-graphics.el: (&ldquo;o&rdquo; &ldquo;Set Output File…&rdquo; calc-graph-output
-   [ ] casual-graphics.el: (&ldquo;Q&rdquo; &ldquo;Quit Gnuplot Session&rdquo; calc-graph-quit :transient nil)


## TODO casual-financial.el <code>[0/6]</code>

-   [ ] casual-financial.el: (&ldquo;%&rdquo; &ldquo;%&rdquo; calc-percent :transient t)
-   [ ] casual-financial.el: (&ldquo;c&rdquo; &ldquo;→%&rdquo; calc-convert-percent :transient t)
-   [ ] casual-financial.el: (&ldquo;D&rdquo; &ldquo;Δ%&rdquo; calc-percent-change :transient t)
-   [ ] casual-financial.el: (&ldquo;`" "`&rdquo; calc-evaluate :transient t)]
-   [ ] casual-financial.el: (&ldquo;R&rdquo; &ldquo;Refresh&rdquo; calc-refresh :transient t)
-   [ ] casual-financial.el: (&ldquo;L&rdquo; &ldquo;Last&rdquo; calc-last-args :transient t)]]


# Estimates

| Estimates |       |
|--------- |----- |
| 19        |       |
| 3         |       |
| 5         |       |
| 8         |       |
| 15        |       |
| 4         |       |
| 5         |       |
| 8         |       |
| 4         |       |
| 3         |       |
| 12        |       |
| 5         |       |
| 15        |       |
| 61        |       |
| 7         |       |
| 7         |       |
| 6         |       |
| 187       | Total |

**Comment by kickingvegas** [comment]
Decided scope is too large to make 1.4.0 release. Reducing scope to cover only main menu. Will break unfinished work into separate tickets and prioritize accordingly for subsequent releases.
